name: 'Auto Integration'
on:
  workflow_dispatch:
    inputs:
      input:
        description: "Test"
        required: false
        default: "World"
jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Run script file
      run: ./test.bash
      shell: bash
